---
AWSTemplateFormatVersion: "2010-09-09"
Description: Generates the lab version of the bulk_load_csv scenario, creates role bucket and table. User only focuses on Lambda and its trigger
Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
  LambdaDBRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: base
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: '*'
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource: !Sub
                  - ${BucketARN}/*
                  - BucketARN: !GetAtt SourceBucket.Arn
              - Effect: Allow
                Action:
                  - "dynamodb:*"
                Resource: !GetAtt DynamoMovieTable.Arn
  DynamoMovieTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'Year'
          AttributeType: 'N'
        -
          AttributeName: 'Title'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'Year'
          KeyType: HASH
        -
          AttributeName: 'Title'
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: 'Movies'
Outputs:
  BucketARN:
    Value: !GetAtt SourceBucket.Arn
  DynamoARN:
    Value: !GetAtt DynamoMovieTable.Arn
  RoleARN:
    Value: !GetAtt LambdaDBRole.Arn
